version: '3.4'

services:
  financemanagement.api:
    image: ${DOCKER_REGISTRY-}financemanagementapi
    build:
      context: .
      dockerfile: FinanceManagement.Api/Dockerfile
    depends_on:
      - financemanagement.db

  financemanagement.db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "avon1_123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
